/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pkh;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Me
 */
public class DataRumahPesertaPKH extends javax.swing.JInternalFrame {
 public static Connection con;
   public static Statement stm;
   public static ResultSet res;
    /**
     * Creates new form DataPesertaPKH
     */
    public DataRumahPesertaPKH() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        koneksimysql();
        tampiltabel();
        tampiltabel2();
        
        jTable_Display_Users.getTableHeader().setOpaque(true);
        jTable_Display_Users.setRowHeight(25);
        jTable_Display_Users.getTableHeader().setBackground(Color.blue);
        jTable_Display_Users2.getTableHeader().setOpaque(true);
        jTable_Display_Users2.setRowHeight(25);
        jTable_Display_Users2.getTableHeader().setBackground(Color.blue);
    }

     public void koneksimysql(){
       try{
           String url = "jdbc:mysql://localhost:3306/pkh";
           String user = "root";
           String pass = "";
           Class.forName("com.mysql.jdbc.Driver");
           con = (Connection) DriverManager.getConnection(url, user, pass);
           stm=(Statement) con.createStatement();
           
       }catch(Exception e){
           System.out.println("koneksi gagal" +e.getMessage());
       }
    }
    
       public void tampiltabel(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Nama Pendamping");
        tb.addColumn("No. HP");
        tb.addColumn("ID Peserta PKH");
        tb.addColumn("Nama Peserta");
        tb.addColumn("Alamat Rumah");
        tb.addColumn("Status Rumah");
        tb.addColumn("Kelurahan");
        tb.addColumn("Kecamatan");
        jTable_Display_Users.setModel(tb);
        
        try{
        res=stm.executeQuery("select * from rumahpesertapkh");
        while(res.next()){
           tb.addRow(new Object[]{
               res.getString("Nama_Pendamping"),
               res.getString("No_Telepon"),
               res.getString("ID_Peserta_PKH"),
               res.getString("Nama_Peserta"),
               res.getString("Alamat_Rumah"),
               res.getString("Status_Rumah"),
               res.getString("Kelurahan"),
               res.getString("Kecamatan"),
           });
        }
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, "data gagal ditampilkan" +e.getMessage());
        }
    }
       
     public void tampiltabel2(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Nama Peserta");
        tb.addColumn("Nama Suami");
        tb.addColumn("Anak Ke 1");
        tb.addColumn("Anak Ke 2");
        tb.addColumn("Anak Ke 3");
        tb.addColumn("Anak Ke 4");
        tb.addColumn("Anak Ke 5");
        tb.addColumn("Anak Ke 6");
        tb.addColumn("Anak Ke 7");
        tb.addColumn("Anak Ke 8");
        jTable_Display_Users2.setModel(tb);
        
        try{
        res=stm.executeQuery("select * from keluargapesertapkh");
        while(res.next()){
           tb.addRow(new Object[]{
               res.getString("Nama_Peserta"),
               res.getString("Nama_Suami"),
               res.getString("Anak_1"),
               res.getString("Anak_2"),
               res.getString("Anak_3"),
               res.getString("Anak_4"),
               res.getString("Anak_5"),
               res.getString("Anak_6"),
               res.getString("Anak_7"),
               res.getString("Anak_8"),
           });
        }
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, "data gagal ditampilkan" +e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Users = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Display_Users2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable_Display_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Display_Users.setShowHorizontalLines(true);
        jTable_Display_Users.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable_Display_Users);

        jTable_Display_Users2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Display_Users2.setShowHorizontalLines(true);
        jTable_Display_Users2.setShowVerticalLines(true);
        jScrollPane2.setViewportView(jTable_Display_Users2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Data Rumah Peserta PKH");

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+ Tambahkan Data Rumah Peserta PKH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("+ Tambahkan Data Anggota Keluarga Harapan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Data Anggota Keluarga PKH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(16, 16, 16)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(888, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1185, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormRumahPesertaPKH next =  new FormRumahPesertaPKH();
        next.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FormAnggotaKeluargaPKH next =  new FormAnggotaKeluargaPKH();
        next.show();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_Display_Users;
    private javax.swing.JTable jTable_Display_Users2;
    // End of variables declaration//GEN-END:variables
}
