/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkh;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import static pkh.MainPage.a;
import static pkh.MainPage.b;
import static pkh.MainPage.c;
/**
 *
 * @author Me
 */
public class FormKSM extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form DataPKH
     */
    public FormKSM() {
        initComponents();
        datatable();
        ActionListener ac1=new ActionListener(){
           @Override public void actionPerformed(ActionEvent e){
             a=lb1MovingText.getText();
             b=a.substring(0, 1);
             c=a.substring(1, a.length());
             lb1MovingText.setText(c+b);
           }
        }; new javax.swing.Timer(400, ac1).start();
    }

     protected void aktif(){
        tid.setEnabled(true);
        tname.setEnabled(true);
        tnik.setEnabled(true);
        tart.setEnabled(true);
        talamat.setEnabled(true);
        trtrw.setEnabled(true);
        tname.requestFocus();
    }
    
    protected void kosong(){
        tid.setText("");
        tname.setText("");
        tnik.setText("");
        tart.setText("");
        talamat.setText("");
        trtrw.setText("");
        cmbkelurahan.setSelectedIndex(0);
        cmbkecamatan.setSelectedIndex(0);
    }
    
    protected void datatable(){
        Object[] Baris ={"id","Nama", "NIK", "Jumlah art", "Alamat", "RT/RW", "Kelurahan","Kecamatan"};
        tabmode  = new DefaultTableModel(null, Baris);
        
        String sql = "select * from pesertapkh";
        try{
           java.sql.Statement stat = conn.createStatement();
           ResultSet hasil = stat.executeQuery(sql);
           while(hasil.next()){
              String a = hasil.getString("id");
              String b = hasil.getString("Nama");
              String c = hasil.getString("NIK");
              String d = hasil.getString("Jumlah_art");
              String e = hasil.getString("Alamat");
              String f = hasil.getString("RT_RW");
              String g = hasil.getString("Kelurahan");
              String h = hasil.getString("Kecamatan");
           }
           
        }catch(Exception e){
           
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tname = new javax.swing.JTextField();
        tnik = new javax.swing.JTextField();
        tart = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        talamat = new javax.swing.JTextField();
        trtrw = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bdelete = new javax.swing.JButton();
        bsave = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        cmbkelurahan = new javax.swing.JComboBox<>();
        cmbkecamatan = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        lb1MovingText = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel1MouseWheelMoved(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        jPanel4.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 193, -1));

        tnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnikActionPerformed(evt);
            }
        });
        jPanel4.add(tnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 193, -1));
        jPanel4.add(tart, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 193, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIK");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah ART");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));
        jPanel4.add(talamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 193, -1));
        jPanel4.add(trtrw, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 193, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kelurahan");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RT/RW");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kecamatan");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        bdelete.setBackground(new java.awt.Color(255, 0, 0));
        bdelete.setForeground(new java.awt.Color(255, 255, 255));
        bdelete.setText("DELETE");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        jPanel4.add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 95, -1));

        bsave.setBackground(new java.awt.Color(0, 0, 255));
        bsave.setForeground(new java.awt.Color(255, 255, 255));
        bsave.setText("SAVE");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel4.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 95, -1));

        bcancel.setBackground(new java.awt.Color(0, 153, 0));
        bcancel.setForeground(new java.awt.Color(255, 255, 255));
        bcancel.setText("Kembali ke Halaman Sebelumnya");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });
        jPanel4.add(bcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 220, -1));

        bedit.setBackground(new java.awt.Color(153, 153, 0));
        bedit.setForeground(new java.awt.Color(255, 255, 255));
        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        jPanel4.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 95, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Masukkan Data Form KSM");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 556, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        jPanel4.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 190, -1));

        cmbkelurahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Cibubur", "Baros", "Babakan", "Subangjaya", "Cikondang", "Gunung Fuyuh", "Cikundul", "Kemang " }));
        jPanel4.add(cmbkelurahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 120, -1));

        cmbkecamatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Ciracas", "Baros", "Cibeureum", "Cikole", "Citamiang", "Gunung Puyuh", "Lembur Situ", "Warudoyong", "Kemang" }));
        cmbkecamatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkecamatanActionPerformed(evt);
            }
        });
        jPanel4.add(cmbkecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 120, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background+.jpeg"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 460));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 460));

        lb1MovingText.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 18)); // NOI18N
        lb1MovingText.setForeground(new java.awt.Color(255, 0, 0));
        lb1MovingText.setText("                                                                                  Form Peserta PKH !!!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lb1MovingText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb1MovingText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel1MouseWheelMoved
        // TODO add your handling code here
       
        

    }//GEN-LAST:event_jPanel1MouseWheelMoved

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        // TODO add your handling code here:
        String sql = "insert into pesertapkh value (?,?,?,?,?,?,?,?)";
        try {
           PreparedStatement stat = conn.prepareStatement(sql);
           stat.setString(1, tid.getText());
           stat.setString(2, tname.getText());
           stat.setString(3, tnik.getText());
           stat.setString(4, tart.getText());
           stat.setString(5, talamat.getText());
           stat.setString(6, trtrw.getText());
           stat.setString(7, cmbkelurahan.getSelectedItem().toString());
           stat.setString(8, cmbkecamatan.getSelectedItem().toString()); 
           stat.executeUpdate();
           
           JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
           kosong();
           tid.requestFocus();
           datatable();
           
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal Disimpan"+e);
        }
        
    }//GEN-LAST:event_bsaveActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from pesertapkh where id = '"+tid.getText()+"'";
            try{
               PreparedStatement stat = conn.prepareStatement(sql);
               stat.executeUpdate();
               JOptionPane.showMessageDialog(null, "data berhasil dihapus");
               kosong();
               tid.requestFocus();
               datatable();
            }catch (SQLException e){
               JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void tnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnikActionPerformed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "update pesertapkh set Nama=?, NIK=?,Jumlah_art=?, Alamat=?, RT_RW=?, Kelurahan=?, Kecamatan=? where id=?";
            PreparedStatement stat = conn.prepareStatement (sql);
            stat.setString(1, tname.getText());
            stat.setString(2, tnik.getText());
            stat.setString(3, tart.getText());
            stat.setString(4, talamat.getText());
            stat.setString(5, trtrw.getText());
            stat.setString(6, cmbkelurahan.getSelectedItem().toString());
            stat.setString(7, cmbkecamatan.getSelectedItem().toString());
            stat.setString(8, tid.getText());
            stat.executeUpdate();
           
           JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
           kosong();
           tid.requestFocus();
           datatable();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal diubah"+e);
        }
        
            
        
    }//GEN-LAST:event_beditActionPerformed

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        // TODO add your handling code here:
        DataPesertaPKH dppkh = new DataPesertaPKH();
        dppkh.show();
        
        dispose();
    }//GEN-LAST:event_bcancelActionPerformed

    private void cmbkecamatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkecamatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkecamatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKSM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bsave;
    private javax.swing.JComboBox<String> cmbkecamatan;
    private javax.swing.JComboBox<String> cmbkelurahan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lb1MovingText;
    private javax.swing.JTextField talamat;
    private javax.swing.JTextField tart;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tnik;
    private javax.swing.JTextField trtrw;
    // End of variables declaration//GEN-END:variables
}
