/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkh;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Me
 */
public class FormLaporanKegiatan extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form FormLaporanKegiatan
     */
    public FormLaporanKegiatan() {
        initComponents();
    }

    protected void aktif(){
        id_pendamping.setEnabled(true);
        npendamping.setEnabled(true);
        tlpn.setEnabled(true);
        wkegiatan.setEnabled(true);
        nkegiatan.setEnabled(true);
        id_peserta.setEnabled(true);
        npeserta.setEnabled(true);
        id_pendamping.requestFocus();
    }
    
    protected void kosong(){
        id_pendamping.setText("");
        npendamping.setText("");
        tlpn.setText("");
        wkegiatan.setText("");
        nkegiatan.setText("");
        id_peserta.setText("");
        npeserta.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        id_pendamping = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        npendamping = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tlpn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        wkegiatan = new javax.swing.JTextField();
        nkegiatan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        npeserta = new javax.swing.JTextField();
        id_peserta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bsave = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_pendamping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pendampingActionPerformed(evt);
            }
        });
        jPanel2.add(id_pendamping, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 220, -1));

        jLabel1.setText("ID Pendamping");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel2.setText("Nama Pendamping");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));
        jPanel2.add(npendamping, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 220, -1));

        jLabel3.setText("No. Telepon");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        jPanel2.add(tlpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 220, -1));

        jLabel4.setText("Waktu Kegiatan");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel5.setText("Nama Kegiatan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        jPanel2.add(wkegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 220, -1));
        jPanel2.add(nkegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 220, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 51, 760, 320));

        jLabel6.setText("Nama Peserta");

        npeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npesertaActionPerformed(evt);
            }
        });

        id_peserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pesertaActionPerformed(evt);
            }
        });

        jLabel7.setText("ID Peserta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(104, 104, 104)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(id_peserta, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npeserta, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_peserta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npeserta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 760, 110));

        bsave.setText("SAVE");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel1.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, -1, -1));

        bedit.setText("EDIT DATA");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        jPanel1.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, -1, -1));

        bdelete.setText("DELETE");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, -1));

        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void npesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npesertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npesertaActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO laporankegiatan VALUES (?,?,?,?,?,?,?)";
        try {
           PreparedStatement stat = conn.prepareStatement(sql);
           stat.setString(1, id_pendamping.getText());
           stat.setString(2, npendamping.getText());
           stat.setString(3, tlpn.getText());
           stat.setString(4, wkegiatan.getText());
           stat.setString(5, nkegiatan.getText());
           stat.setString(6, id_peserta.getText());
           stat.setString(7, npeserta.getText());
      
           stat.executeUpdate();
           
           JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
           kosong();
           id_pendamping.requestFocus();
         
           
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal Disimpan"+e);
        }

    }//GEN-LAST:event_bsaveActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "update laporankegiatan set Nama_Pendamping=?, Telepon=?, Waktu_Kegiatan=?, Nama_Kegiatan=?, Id_peserta=?, Nama_Peserta=? where id=?";
            PreparedStatement stat = conn.prepareStatement (sql);
           
           stat.setString(1, npendamping.getText());
           stat.setString(2, tlpn.getText());
           stat.setString(3, wkegiatan.getText());
           stat.setString(4, nkegiatan.getText());
           stat.setString(5, id_peserta.getText());
           stat.setString(6, npeserta.getText());
           stat.setString(7, id_pendamping.getText());
           stat.executeUpdate();
           
           JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
           kosong();
           id_pendamping.requestFocus();
           
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal diubah"+e);
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
               int ok = JOptionPane.showConfirmDialog(null, "hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from laporankegiatan where id = '"+id_pendamping.getText()+"'";
            try{
               PreparedStatement stat = conn.prepareStatement(sql);
               stat.executeUpdate();
               JOptionPane.showMessageDialog(null, "data berhasil dihapus");
               kosong();
               id_pendamping.requestFocus();
            }catch (SQLException e){
               JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void id_pendampingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pendampingActionPerformed
        // TODO add your handling code here:
         try {

            String sql = "SELECT * FROM pendampingpkh where id='"
                    + id_pendamping.getText() + "'";
            
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                npendamping.setText(res.getString("Nama"));
                tlpn.setText(res.getString("No_HP"));
                
                
            }

        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());

        }
    }//GEN-LAST:event_id_pendampingActionPerformed

    private void id_pesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pesertaActionPerformed
        // TODO add your handling code here:
        try {

            String sql = "SELECT * FROM pesertapkh where id='"
                    + id_peserta.getText() + "'";
            
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                npeserta.setText(res.getString("Nama")); 
            }

        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());

        }
    }//GEN-LAST:event_id_pesertaActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        LaporanKegiatan backpage = new LaporanKegiatan();
        backpage.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporanKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporanKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporanKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporanKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporanKegiatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bsave;
    private javax.swing.JTextField id_pendamping;
    private javax.swing.JTextField id_peserta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nkegiatan;
    private javax.swing.JTextField npendamping;
    private javax.swing.JTextField npeserta;
    private javax.swing.JTextField tlpn;
    private javax.swing.JTextField wkegiatan;
    // End of variables declaration//GEN-END:variables
}
